name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_markdown: ^0.7.0
  google_generative_ai: ^0.4.7 # Usa la versión más reciente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  fl_chart: ^0.68.0

flutter:
  uses-material-design: true
